version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - quiz-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - quiz-network

  app:
    build: 
      context: ./server  
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db
    networks:
      - quiz-network
    command: >
      sh -c "dockerize -wait tcp://${DB_HOST}:${DB_PORT} -timeout 60s &&
             npm run start:prod"

  client:
    build:
      context: ./client  
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  db_data:
